services:
  db_postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mock_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 512M
    restart: unless-stopped

volumes:
  pgdata: